### ISSUE TITLE
UX Task-1

### ISSUE THREAD

**Issue by rishika-g31** [opencodeiiita/FitLife#1]
OPEN TO ALL. 
No need to claim this issue.
NO SUBMISSION WILL BE ACCEPTED AFTER 16th December 11:59 PM.

This first task is based on basic understanding of User Experience and User flow. 

FitLife💪 is a versatile and user-friendly fitness app that is designed to help you lead a healthier and more active life. Whether you're an experienced fitness enthusiast or just starting out on your fitness journey, FitLife has something for everyone✅ . It keeps you Connected with certified fitness trainers and mentors who can provide you with personalized guidance. It offers customized workout plans that match your fitness level and goals and also sets dietary goals and monitor your macronutrient intake and helps you visualize your fitness journey🚀.

<aside>
💡 The task needs to be done in FigJam. There is no need to download FigJam because it is free to use. It is quite simple to learn and only takes around 15 minutes. If you are not sure on how to use it, check the tutorial here: https://www.youtube.com/watch?v=RVNuArHH5WM

</aside>

<br>

## Procedure:

1. Think about how the flow of the app will be for an average user who has just installed this app and is opening this app for the first time. The user is assumed to be unclear with the functionalities of the app.🤔
2. You have to decide how the user will move through the app, what steps will he/she need to take and in which order, for eg. the user first might need to sign up for the app.
3. You can add a range of features designed to help users track, improve, and maintain their health and fitness goals.
4. Finally create your ideal user flow in a FigJam file and provide its link (in .txt file). Submit your txt files in the UX task-1 folder only.

If you are unclear with user flow diagrams check this short video here: https://www.youtube.com/watch?v=cvYhuowazh0 

<br>

## MDC (Minimum Design Criteria)

The user flow can be very basic but it at least needs to fulfil the basic functionality of the app that is the end result should be that the needy gets connected to the donor and vice-versa. The flow should begin from user entering the app for first time. If the user wants to track activities like steps and calories, get guidance and personalized workout plans. It should cater to various aspects of fitness, from workouts to nutrition and community support, helping users achieve their health objectives.✅

For any doubts related to the task or the submission process, you can always ping us on discord. Use the tag @fitlife to notify the mentors. We will be happy to help.😊

**Comment by shrutikarathi6** [comment]
claim

**Comment by rishika-g31** [comment]
Hi! It's an open for all issue no need to claim. Keep contributing!🚀
