### ISSUE TITLE
UX Task-2

### ISSUE THREAD

**Issue by rishika-g31** [opencodeiiita/FitLife#107]
**OPEN TO ALL.** 

**NO NEEED TO CLAIM. NO SUBMISSION WILL BE ACCEPTED AFTER  21st DEC 11:59PM.**

**Wireframing is a schematic blueprint; a visual guide that represents the app layout, the flow between the screens and its functional representation informed by your business objective**.🧑‍🚒

Our next task in this FitLife**💪** App Design Repo is to design wireframe for the fitness app. Do check out this tutorial and read the blog to know about what is wireframing within app design.✅

[https://www.youtube.com/watch?v=goPCYWvpnUI](https://www.youtube.com/watch?v=qpH7-KFWZRI)

https://www.figma.com/blog/how-to-wireframe/

Attaching below an image to show how a wireframe of an app looks like 👇
<br>

![op3](https://github.com/opencodeiiita/FitLife/assets/120507340/b86a0834-5762-4a18-b36a-685474fb1276)

## Submission Guideline:

- Design wireframes for FitLife💪 app based on your understanding of the app from the given user flow : (best userflow from UX Task-1)
    - https://www.figma.com/file/i7fDfh9DLE42qNoiBvEXn0/Untitled?type=whiteboard&node-id=0%3A1&t=RPPVSEv73rCXIJUN-1 ( **Special thanks to @AditiGupta976** for contributing this great user flow in the first task)
- The Wireframe design should go with the userflow provided.
- Submit the Figma file link in a .txt folder and submit the file in UX Task - 2 folder ONLY.

## Minimum Design Criteria (MDC)

 Since it is a **20 point task**, do read and fulfil the MDC accordingly.

- Design the Wireframes for **atleast 4** screens of the app including all the necessary functions of the app.✅
- Your design should have a consistent theme across all of the screens.
- You can take inspiration from the internet and implement it using your own perspective and approach.

**NOTE:** Strict plagarism is applied so **Do not COPY PASTE** other’s idea. Copying and submitting other’s idea just for points is useless. The motive of Opencode is to learn and not to copy.😊

If some of these things appear complex to you, don't worry too much 😅. Since creating wireframes is a form of art in and of itself, beginners may find the process intimidating. You can ping us on discord in the FitLife**💪** channel and we will be happy to help you with your queries.

 Keep Learning! 🚀

**Comment by Varunhrdcr** [comment]
UX Task 2 done

**Comment by Varunhrdcr** [comment]
https://www.figma.com/file/6pHlSeTiRZNG9DC8sIOt4o/UX-TASK-2?type=design&node-id=0%3A1&mode=design&t=eUBuLfdSUkxOZDDG-1
