### ISSUE TITLE
button-Task

### ISSUE THREAD

**Issue by rishika-g31** [opencodeiiita/FitLife#108]
**OPEN TO ALL. NO NEED TO CLAIM. NO SUBMISSION WILL BE ACCEPTED AFTER 18TH DEC 6pm.**

While you are working on the Wireframes for the FitLife💪 app, here is another short task to test your thinking 🤔 as User Interface Designer!.

Buttons are the primary way users interact with interfaces. They need to be easily identifiable 👀, appropriately sized, and placed in intuitive locations. A well-designed button makes it clear what action will occur when clicked or tapped.✅

In this task you have to use basic shapes to create interesting buttons🔘. All you need to do is to copy that button exactly same.👇

<img width="248" alt="op5 (1)" src="https://github.com/opencodeiiita/FitLife/assets/120507340/49fe4f8f-0d8c-4c40-9ee4-d72d455c2110">

 If you are unclear with how to start, you can check this video:

https://youtu.be/uKT9pFigb88?si=6UW5LHRPzlP4M3r2

<aside>
💡 This task can be done in **Adobe Illustrator** or **Figma.**

</aside>

## **Submission Guideline:**

- *Upload the illustrator file( if doing in illustrator )* or a *.txt file (with figma link in it)* under the "Button-Task" Folder only.

> This task is for 5 points.
> 

NOTE: Create the buttons on your own and **do not copy paste** from others file.💀

 Remember: The motive of Opencode is to learn.😊

## **MDC (Minimum Design Criteria):**

The buttons should look appealing and should be exactly same as the image provided.

For any doubts related to the task or the submission process you can always ping us on discord. We will be happy to help.😊

**Comment by AngadManroy** [comment]
Claim
