### ISSUE TITLE
Short UI Task

### ISSUE THREAD

**Issue by rishika-g31** [opencodeiiita/FitLife#191]
> This is a **COMPETETIVE ISSUE. ⭐ The top 3 logos will only be given points**

1. 1st prize- 20 points
2.  2nd prize- 15 points
3.  3rd prize- 10 points

**OPEN TO ALL. NO NEED TO CLAIM. NO SUBMISSION WILL BE ACCEPTED AFTER 23rd Dec 11.59pm.**

The task is to re-design the logo for the **SemBreaker app.✏️** (Our college app where all Study Materials, Previous year questions and notes for every particular course of the sem are provided.)

  

<aside>
💡 This task can be done in  Adobe Illustrator or Figma.

</aside>

If you are unclear with how to start, you can check out these articles: 
1. https://www.ebaqdesign.com/blog/logo-design-process  

2. https://99designs.com/blog/tips/logo-design-process-how-professionals-do-it/

or check out this playlist:
https://www.youtube.com/watch?v=NfkQeOSmIMY&list=PLW-zSkCnZ-gDer-VZlBbe1f9-G0zNYdtg

**Submission Guidelines:**

For Submission, you would have to *Upload the illustrator file( if doing in illustrator )* or a *.txt file (with figma link in it)* and make sure to keep the file in the "**Short UI Task”** folder only. You need to add a jpg or png file of your work in the PR.

Any kind of plagiarism will not be supported. You can take inspiration, but the idea must be unique.😊

**MDC (Minimum Design Criteria):**

The design should be appropriate, consistent, and clean. These points must be kept in mind, the logo should be: Simple, Versatile, Timeless, Memorable, and Scalable.✅

For any doubts related to the task or the submission process you can always ping us on discord. We will be happy to help.

**Comment by abhisheksharma010** [comment]
Claim
