### ISSUE TITLE
FitLife x GeekHavenApp-LOGO

### ISSUE THREAD

**Issue by rishika-g31** [opencodeiiita/FitLife#201]
This is a **COMPETETIVE ISSUE. ⭐ The top 3 logos will only be given points**

1. 1st prize- 20 points
2.  2nd prize- 15 points
3.  3rd prize- 10 points

**OPEN TO ALL. NO NEED TO CLAIM. NO SUBMISSION WILL BE ACCEPTED AFTER 24th Dec 11.59pm.**

**GeekHaven Commmunity App is a one-stop app for all the management tasks of GeekHaven.🌌**

This app provides a comprehensive space where teams can discuss their ideas, display the current running projects of different wings for better collaboration.🧑‍💻

The task is to design the **logo** for the **GeekHaven Commmunity App.**

Providing you with the logo of GeekHaven..make your design accordingly. 
 
<br>

<img width="304" alt="logo" src="https://github.com/opencodeiiita/FitLife/assets/120507340/bc319eab-8df4-494f-a923-8d010aea714d">

<br>
<br>

<aside>
💡 This task can be done in Adobe Illustrator or Figma.

</aside>

If you are unclear with how to start, you can check out these articles: 
1. https://www.ebaqdesign.com/blog/logo-design-process  

2. https://99designs.com/blog/tips/logo-design-process-how-professionals-do-it/

or check out this playlist:
https://www.youtube.com/watch?v=NfkQeOSmIMY&list=PLW-zSkCnZ-gDer-VZlBbe1f9-G0zNYdtg

**Submission Guidelines:**

For Submission, you would have to *Upload the illustrator file( if doing in illustrator )* or a *.txt file (with figma link in it)* and make sure to keep the file in the "**GeekhavenApp-logo”** folder only.

Any kind of plagiarism will not be supported. You can take inspiration, but the idea must be unique.😊

**MDC (Minimum Design Criteria):**

The design should be appropriate, consistent, and clean. These points must be kept in mind, the logo should be: Simple, Versatile, Timeless, Memorable, and Scalable.✅

For any doubts related to the task or the submission process you can always ping us on discord. We will be happy to help.😊

**Comment by chiragmalik2612** [comment]
claim

**Comment by abhisheksharma010** [comment]
Calim

**Comment by rishika-g31** [comment]
No need to claim... it is open-for-all.
