### ISSUE TITLE
FitLife x GeekHavenApp-Feed

### ISSUE THREAD

**Issue by rishika-g31** [opencodeiiita/FitLife#202]
**Open to all. No need to claim. No submission will be considered after 27th Dec 11.59pm.**

**GeekHaven Commmunity App is a one-stop app for all the management tasks of GeekHaven.🌌**

This app provides a comprehensive space where teams can discuss their ideas, display the current running projects of different wings for better collaboration.🧑‍💻

In this Task you need to design the **homepage for the** **GeekHaven Commmunity App.📱**

Design the homescreen of the app in a way that seems suitable to you based on the purpose of the GeekHaven Commmunity App.

If you are unclear with how to start, you can check out this playlist:
https://youtu.be/hyZIcCAl8sw?si=51AQCdhlt5byCoEJ

## Submission Guideline:

- The screen would be used to show all the feed which includes post from the other users.
    Like all the news a developer needs to here would be given in that feed.📰 (Like the one in instagram ).

- It should show also display ongoing projects of the users.🧑‍💻
- The content of the screens can vary as per your understanding of the purpose of the app.
- You can take inspiration from the **tumblr app.**
- The screens must have proper consistency in terms of fonts colours and imagery
- Submit the link to the figma file in a .txt file and place the file in ‘GeekhavenApp-Feed' folder only.

## Minimum Design Criteria

Since you have completed a lot of UI and UX tasks already, you must have gotten a fair idea of what comprises a good UI and what doesn't look good. Being a 20 pointer you have to yourself decide what looks good enough to get merged and what doesn't. Final decision resides with mentors and organisers same as all the previous task. 😊

**Comment by abhisheksharma010** [comment]
Claim

**Comment by rishika-g31** [comment]
No need to claim..it's open-for-all.
