### ISSUE TITLE
FitLife x GeekHavenApp-Projects

### ISSUE THREAD

**Issue by rishika-g31** [opencodeiiita/FitLife#208]
**Open to all. No need to claim. No submission will be considered after 27th Dec 11.59pm.**

**GeekHaven Commmunity App is a one-stop app for all the management tasks of GeekHaven.🌌**

This app provides a comprehensive space where teams can discuss their ideas, display the current running projects of different wings for better collaboration.🧑‍💻

In this Task you need to design the **project** **page for the** **GeekHaven Commmunity App.📱**

Design the project screen of the app in a way that seems suitable to you based on the purpose of the GeekHaven Commmunity App.

If you are unclear with how to start, you can check out this playlist:
https://youtu.be/hyZIcCAl8sw?si=51AQCdhlt5byCoEJ

## Submission Guideline:

- The screen is used to manage all the ongoing projects.🧑‍💻
- It should display the ongoing projects.
- It should have a option to create a new project.
- The progress/completeness of the project should be visually represented using progress bars.📈
- The content of the screens can vary as per your understanding of the purpose of the app.
- You can take inspiration from the **tumblr app.**
- The screens must have proper consistency in terms of fonts colours and imagery
- Submit the link to the figma file in a .txt file and place the file in ‘GeekhavenApp-Project’ folder only.

## Minimum Design Criteria

Since you have completed a lot of UI and UX tasks already, you must have gotten a fair idea of what comprises a good UI and what doesn't look good. Being a 30 pointer you have to yourself decide what looks good enough to get merged and what doesn't. Final decision resides with mentors and organisers same as all the previous task. 😊

**Comment by kushal7201** [comment]
Claim
