### ISSUE TITLE
UI Task-1

### ISSUE THREAD

**Issue by rishika-g31** [opencodeiiita/FitLife#250]
**OPEN TO ALL**

**No need to claim this issue. NO SUBMISSION WILL BE ACCEPTED AFTER 5th Jan 11:59 PM**

Your next task in this FitLife**💪** App Design Repo is to design the **Onboarding screens📱** for the fitness app. Do check out this tutorial to know about what is onboarding within app design https://youtu.be/yvwtITLVsP4?si=zXZ5T2si52u4QxVp

You can search for vectors from Freepik/Unsplash and take inspiration.

![op10](https://github.com/opencodeiiita/FitLife/assets/120507340/d0e13f5f-ec7c-4e36-8767-cd0657b31eb1)

The below image is an example of the onboarding screen. You have to design similar design that will be suitable for **the onboarding screens of FitLife app**.💪

If you are unclear with how to start, you can check out these articles: 
1. https://www.ebaqdesign.com/blog/logo-design-process  2. https://99designs.com/blog/tips/logo-design-process-how-professionals-do-it/

or check out this playlist:
https://youtu.be/yvwtITLVsP4?si=zXZ5T2si52u4QxVp

## Submission Guideline:

- Design onboarding screens (Minimum 3) for FitLife app based on your understanding of the app. ✅
- Submit the Figma file link in a .txt folder and submit the file in UI Task - 1 folder ONLY.

Any kind of plagiarism will not be supported. You can take inspiration, but the idea must be unique.

**MDC (Minimum Design Criteria):**

The design must be suitable, constant, and tidy. The illustration/graphic shouldn't be unrelated to the app's functionality and must be tied to the FitLife theme.✅

For any doubts related to the task or the submission process you can always ping us on discord. We will be happy to help.😊

**Comment by Apoorv012** [comment]
ckai
