### ISSUE TITLE
College ID

### ISSUE THREAD

**Issue by rishika-g31** [opencodeiiita/FitLife#269]
**OPEN TO ALL. NO NEED TO CLAIM. NO SUBMISSION WILL BE ACCEPTED AFTER 9th Jan 11.59pm.**

**Proof of Existence in the University Circus-** The holder of this card is a certified multitasker🏃‍♂️ , adept at balancing academic pursuits, social engagements, and an ever-expanding task list📈 . Embracing the whirlwind of college life with a smile, a steaming cup of coffee, and an unshakable faith in the restorative abilities of a well-deserved night's sleep... eventually.🤐

**The task is to make a new college ID or try to duplicate the existing id as closest as possible.🪪**

If you are unclear with how to start, you can check out these articles: 
1. https://www.ebaqdesign.com/blog/logo-design-process  

2. https://99designs.com/blog/tips/logo-design-process-how-professionals-do-it/

or check out this playlist:
https://www.youtube.com/watch?v=NfkQeOSmIMY&list=PLW-zSkCnZ-gDer-VZlBbe1f9-G0zNYdtg

**Submission Guidelines:**

For Submission, you would have to *Upload the illustrator file( if doing in illustrator )* or a *.txt file (with figma link in it)* and make sure to keep the file in the "College ID" folder only.

Any kind of plagiarism will not be supported. You can take inspiration, but the idea must be unique.😊

**MDC (Minimum Design Criteria):**

The design should be appropriate, consistent, and clean. These points must be kept in mind, the logo should be: Simple, Versatile, Timeless, Memorable, and Scalable.✅

For any doubts related to the task or the submission process you can always ping us on discord. We will be happy to help.😊

**Comment by Nandinig24** [comment]
we have to make id card or logo
