### ISSUE TITLE
User Perspective

### ISSUE THREAD

**Issue by rishika-g31** [opencodeiiita/FitLife#61]
**OPEN TO ALL.** 

**NO NEEED TO CLAIM. NO SUBMISSION WILL BE ACCEPTED AFTER 16TH DEC 6PM.**

The task is brief and doesn't take much time, but what it actually requires is a strong eye for seeing things from the perspective of the user.👀

From a user's perspective, a well-designed interface feels like a seamless journey. It's like navigating a clear and well-marked path where everything falls effortlessly into place.✅

Ultimately, good UI design prioritizes user needs and ease of use, while bad UI design hampers usability and can drive users away.❌

In the below provided image you need to figure out which UX is more appealing to the user with **2 valid** points.🤔
<br>

![hhhh](https://github.com/opencodeiiita/FitLife/assets/128993800/408d99d1-fc11-452a-894c-6c9ff38c1e36)

## Minimum Design Criteria (MDC)

It is a very basic Task! 😊 You just need to write 2 points explaining as to why one UX is better than the other.

NOTE: **Do not COPY PASTE** other’s idea as it should be your perspective.😊

## Submission Guideline:

- Provide the link of google docs in a .txt file. Make sure that the link is accessible (and not private).
- Submit your txt files in the 'User Perspective' folder only.

Happy UXing contributors!🚀

**Comment by QuantTitan** [comment]
claim

**Comment by rishika-g31** [comment]
Hi! It's an open for all issue no need to claim. Keep contributing!🚀
